# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- main  

pool: my-pc 

variables:
  fastlane_api_token: $(APPCENTER_API_TOKEN)

steps:
- script: |
    gem install bundler
    bundle install
  displayName: 'Install Bundler and dependencies'

# - task: Gradle@2
#   displayName: 'gradlew assembleRelease'
#   inputs:
#     # gradleWrapperFile: 'MobileApp/SourceCode -Android/gradlew'
#     # workingDirectory: 'MobileApp/SourceCode -Android'
#     tasks: assembleRelease

# - task: CopyFiles@2
#   displayName: 'Copy Files to: $(build.artifactStagingDirectory)'
#   inputs:
#     SourceFolder: 'MobileApp/SourceCode -Android'
#     Contents: '**/*.apk'
#     TargetFolder: '$(build.artifactStagingDirectory)'
# # - script: bundle exec fastlane generate_my_apk
# #   displayName: 'Generate APK with Fastlane'

- script: |
    echo "Uploading APK to App Center"
    echo  '$(Agent.DefaultWorkingDirectory)'
    bundle exec fastlane app_center_upload
  displayName: 'Upload APK to App Center'
  env:
    APPCENTER_API_TOKEN: $(APPCENTER_API_TOKEN)  # Pass the environment variable from Azure Pipeline
