# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

dotenv_file = File.expand_path("../../app/src/main/assets/env", __FILE__)
if File.exist?(dotenv_file)
  puts "Loading .env file from: #{dotenv_file}"
  require 'dotenv'
  Dotenv.load(dotenv_file)
  puts "APPCENTER_API_TOKEN loaded: #{ENV["APPCENTER_API_TOKEN"]}"
else
  puts ".env file not found at: #{dotenv_file}"
end

default_platform(:android)

platform :android do

desc "Generate Production Release Apk"
lane :generate_my_apk do
    gradle(
       task: "clean assemble",
       build_type: "Release"
    )
end
#Usage on terminal => fastlane generate_my_apk

before_all do
  Dotenv.overload 'env'
end

desc "App Center Upload"
lane :app_center_upload do
     apk_path = File.expand_path("../../app/build/outputs/apk/release/app-release.apk", __FILE__)
            unless File.exist?(apk_path)
                UI.user_error!("Couldn't find build file at path '#{apk_path}'")
     end
    appcenter_upload(
            api_token: ENV["APPCENTER_API_TOKEN"],
            owner_name: "WaqasAhmed",
            app_name: "fintrack",
            file: apk_path,
            notify_testers: true
    )
end
#usage => fastlane app_center_upload
end
